
services:
  cache_ledger:
    image: redis:7-alpine
    container_name: apex-cache-ledger
    restart: unless-stopped
    ports:
      - "6375:6379"
    networks:
      - banking_network
    labels:
      com.apex.banking.layer: "infrastructure"
      com.apex.banking.service: "redis-cache"

networks:
  banking_network:
    driver: bridge
    labels:
      com.apex.banking.layer: "infrastructure"
      com.apex.banking.service: "redis-cache"